name: K6 Performance Tests
on:
  push:
 
jobs:
  performance-tests:
    runs-on: ubuntu-latest
    env:
      K6_BROWSER_HEADLESS: true
      K6_BROWSER_ENABLED: false
      K6_BROWSER_ARGS: 'no-sandbox'
      K6_BROWSER_EXECUTABLE_PATH: /usr/bin/google-chrome
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Enable cache for system files: https://github.com/actions/toolkit/issues/946
      - name: root suid tar
        run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar

      - name: Cache k6
        id: cache-k6
        uses: actions/cache@v3
        with:
          path: /usr/bin/k6
          key: ${{ runner.os }}-k6

      # cannot use the k6 docker image because it does not allow executing shell commands
      - name: Install k6 in Ubuntu
        if: steps.cache-k6.outputs.cache-hit != 'true'
        run: |  
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Run k6 foundations tests
        run: k6 run --no-thresholds stages.js

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: k6-browser-report-summary-stages
          path: TestReport.html

      - name: Run k6 base tests
        run: k6 run --no-thresholds base.js

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: k6-browser-report-summary-base
          path: TestReport.html