name: K6 Performance Tests
on:
  push:
 
jobs:
  performance-tests:
    runs-on: ubuntu-latest
    env:
      K6_BROWSER_HEADLESS: true
      K6_BROWSER_ARGS: 'no-sandbox'
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      - run: |
          ${{ steps.setup-chrome.outputs.chrome-path }} --version
          /usr/bin/google-chrome --version
          export K6_BROWSER_EXECUTABLE_PATH=/usr/bin/google-chrome
          export K6_BROWSER_HEADLESS=true 
          export K6_BROWSER_ARGS='no-sandbox'

      - name: Run browser k6 test
        uses: grafana/k6-action@v0.3.0
        env:
           K6_BROWSER_EXECUTABLE_PATH: /usr/bin/google-chrome
        with:
         filename: stages.js

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: k6-browser-report-summary-stages
          path: result.html

      - name: Run k6 test on Lambda Test
        uses: grafana/k6-action@v0.3.0
        env:
           K6_BROWSER_EXECUTABLE_PATH: /usr/bin/google-chrome
        with:
         filename: base.js

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: k6-browser-report-summary-base
          path: result.html